import java.time.Clock;
import java.time.DateTimeException;
import java.time.Duration;
import java.time.Instant;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.OffsetTime;
import java.time.ZoneOffset;
import java.time.chrono.HijrahChronology;
import java.time.chrono.IsoChronology;
import java.time.chrono.IsoEra;
import java.time.chrono.JapaneseChronology;
import java.time.chrono.MinguoChronology;
import java.time.chrono.ThaiBuddhistChronology;

/**
 * The twelve java.time members added on 08.10.2026, run on the real library.
 *
 * This is compiled ahead of time against robovm-rt and executed as a native binary, so the
 * java.time it exercises is the one a phone gets — libcore's, which has diverged from OpenJDK's
 * for fifteen years. check.sh next door cannot ask this question: it transplants a copy of a
 * member into a probe package, which proves only that a copy of OpenJDK agrees with OpenJDK.
 *
 * Every expected value below was generated by running the same expression on a real JDK 25 and
 * printing it, not typed. Dates are the one subject where a plausible-looking number is almost
 * always wrong by a day or an hour, and three of the values here are negative epoch seconds, where
 * nobody's intuition is reliable.
 *
 * The members:
 *
 *   Clock.tickMillis(ZoneId)                              Java 9
 *   Instant.until(Instant)                                Java 23
 *   LocalDate.getEra() narrowed to IsoEra                 Java 22
 *   OffsetTime.toEpochSecond(LocalDate)                   Java 9
 *   Chronology.epochSecond(...) x2, default                Java 9
 *   Chronology.isIsoBased(), default                      Java 19
 *   IsoChronology.epochSecond(...), isIsoBased()          Java 9, 19
 *   Japanese/Minguo/ThaiBuddhist isIsoBased()             Java 19
 */
public class TimeCheck {

    static int checked, failed;

    static void eq(String what, Object got, Object want) {
        checked++;
        if (!String.valueOf(got).equals(String.valueOf(want))) {
            failed++;
            System.out.println("  MISMATCH " + what + ": got " + got + ", wanted " + want);
        }
    }

    static void throwsToo(String what, Class<?> expected, Runnable r) {
        checked++;
        try {
            r.run();
            failed++;
            System.out.println("  MISMATCH " + what + ": nothing thrown, wanted "
                    + expected.getName());
        } catch (Throwable t) {
            if (!expected.isInstance(t)) {
                failed++;
                System.out.println("  MISMATCH " + what + ": " + t.getClass().getName()
                        + ", wanted " + expected.getName());
            }
        }
    }

    public static void main(String[] args) {
        // --- Instant.until(Instant) ---
        eq("Instant.parse(\"2026-03-15T12:00:00Z\").until(Instant.parse(\"2026-03-15T12:00:01Z\")).toString()", Instant.parse("2026-03-15T12:00:00Z").until(Instant.parse("2026-03-15T12:00:01Z")).toString(), "PT1S");
        eq("Instant.parse(\"2026-03-15T12:00:01Z\").until(Instant.parse(\"2026-03-15T12:00:00Z\")).toString()", Instant.parse("2026-03-15T12:00:01Z").until(Instant.parse("2026-03-15T12:00:00Z")).toString(), "PT-1S");
        eq("Instant.ofEpochSecond(0, 999999999).until(Instant.ofEpochSecond(1, 0)).toNanos()", Instant.ofEpochSecond(0, 999999999).until(Instant.ofEpochSecond(1, 0)).toNanos(), 1L);
        eq("Instant.ofEpochSecond(1, 0).until(Instant.ofEpochSecond(0, 999999999)).toNanos()", Instant.ofEpochSecond(1, 0).until(Instant.ofEpochSecond(0, 999999999)).toNanos(), -1L);
        eq("Instant.EPOCH.until(Instant.EPOCH).toString()", Instant.EPOCH.until(Instant.EPOCH).toString(), "PT0S");
        eq("Instant.parse(\"1900-01-01T00:00:00Z\").until(Instant.parse(\"2026-01-01T00:00:00Z\")).toDays()", Instant.parse("1900-01-01T00:00:00Z").until(Instant.parse("2026-01-01T00:00:00Z")).toDays(), 46021L);
        eq("Duration.between(Instant.parse(\"1900-01-01T00:00:00Z\"), Instant.parse(\"2026-01-01T00:00:00Z\")).equals(Instant.parse(\"1900-01-01T00:00:00Z\").until(Instant.parse(\"2026-01-01T00:00:00Z\")))", Duration.between(Instant.parse("1900-01-01T00:00:00Z"), Instant.parse("2026-01-01T00:00:00Z")).equals(Instant.parse("1900-01-01T00:00:00Z").until(Instant.parse("2026-01-01T00:00:00Z"))), true);

        // --- LocalDate.getEra ---
        eq("LocalDate.parse(\"2026-03-15\").getEra().toString()", LocalDate.parse("2026-03-15").getEra().toString(), "CE");
        eq("LocalDate.parse(\"0001-01-01\").getEra().toString()", LocalDate.parse("0001-01-01").getEra().toString(), "CE");
        eq("LocalDate.parse(\"0000-12-31\").getEra().toString()", LocalDate.parse("0000-12-31").getEra().toString(), "BCE");
        eq("LocalDate.parse(\"-0001-06-15\").getEra().toString()", LocalDate.parse("-0001-06-15").getEra().toString(), "BCE");
        eq("LocalDate.parse(\"2026-03-15\").getEra() == IsoEra.CE", LocalDate.parse("2026-03-15").getEra() == IsoEra.CE, true);

        // --- OffsetTime.toEpochSecond(LocalDate) ---
        eq("OffsetTime.parse(\"12:00:00Z\").toEpochSecond(LocalDate.parse(\"1970-01-01\"))", OffsetTime.parse("12:00:00Z").toEpochSecond(LocalDate.parse("1970-01-01")), 43200L);
        eq("OffsetTime.parse(\"12:00:00+02:00\").toEpochSecond(LocalDate.parse(\"2026-03-15\"))", OffsetTime.parse("12:00:00+02:00").toEpochSecond(LocalDate.parse("2026-03-15")), 1773568800L);
        eq("OffsetTime.parse(\"00:00:00-05:00\").toEpochSecond(LocalDate.parse(\"1969-12-31\"))", OffsetTime.parse("00:00:00-05:00").toEpochSecond(LocalDate.parse("1969-12-31")), -68400L);
        eq("OffsetTime.parse(\"23:59:59+05:45\").toEpochSecond(LocalDate.parse(\"2026-12-31\"))", OffsetTime.parse("23:59:59+05:45").toEpochSecond(LocalDate.parse("2026-12-31")), 1798740899L);

        // --- IsoChronology.epochSecond, and the default beside it ---
        eq("IsoChronology.INSTANCE.epochSecond(2026, 3, 15, 12, 0, 0, ZoneOffset.UTC)", IsoChronology.INSTANCE.epochSecond(2026, 3, 15, 12, 0, 0, ZoneOffset.UTC), 1773576000L);
        eq("IsoChronology.INSTANCE.epochSecond(1970, 1, 1, 0, 0, 0, ZoneOffset.UTC)", IsoChronology.INSTANCE.epochSecond(1970, 1, 1, 0, 0, 0, ZoneOffset.UTC), 0L);
        eq("IsoChronology.INSTANCE.epochSecond(1969, 12, 31, 23, 59, 59, ZoneOffset.UTC)", IsoChronology.INSTANCE.epochSecond(1969, 12, 31, 23, 59, 59, ZoneOffset.UTC), -1L);
        eq("IsoChronology.INSTANCE.epochSecond(2024, 2, 29, 0, 0, 0, ZoneOffset.UTC)", IsoChronology.INSTANCE.epochSecond(2024, 2, 29, 0, 0, 0, ZoneOffset.UTC), 1709164800L);
        eq("IsoChronology.INSTANCE.epochSecond(1900, 1, 1, 0, 0, 0, ZoneOffset.ofHours(2))", IsoChronology.INSTANCE.epochSecond(1900, 1, 1, 0, 0, 0, ZoneOffset.ofHours(2)), -2208996000L);
        eq("IsoChronology.INSTANCE.epochSecond(-1, 12, 31, 23, 0, 0, ZoneOffset.UTC)", IsoChronology.INSTANCE.epochSecond(-1, 12, 31, 23, 0, 0, ZoneOffset.UTC), -62167222800L);
        eq("IsoChronology.INSTANCE.epochSecond(IsoEra.BCE, 1, 6, 15, 0, 0, 0, ZoneOffset.UTC)", IsoChronology.INSTANCE.epochSecond(IsoEra.BCE, 1, 6, 15, 0, 0, 0, ZoneOffset.UTC), -62152876800L);

        // --- the non-ISO chronologies go through Chronology's default ---
        eq("MinguoChronology.INSTANCE.epochSecond(115, 3, 15, 12, 0, 0, ZoneOffset.UTC)", MinguoChronology.INSTANCE.epochSecond(115, 3, 15, 12, 0, 0, ZoneOffset.UTC), 1773576000L);
        eq("ThaiBuddhistChronology.INSTANCE.epochSecond(2569, 3, 15, 12, 0, 0, ZoneOffset.UTC)", ThaiBuddhistChronology.INSTANCE.epochSecond(2569, 3, 15, 12, 0, 0, ZoneOffset.UTC), 1773576000L);
        eq("HijrahChronology.INSTANCE.epochSecond(1447, 9, 15, 6, 30, 0, ZoneOffset.UTC)", HijrahChronology.INSTANCE.epochSecond(1447, 9, 15, 6, 30, 0, ZoneOffset.UTC), 1772605800L);

        // --- isIsoBased ---
        eq("IsoChronology.INSTANCE.isIsoBased()", IsoChronology.INSTANCE.isIsoBased(), true);
        eq("JapaneseChronology.INSTANCE.isIsoBased()", JapaneseChronology.INSTANCE.isIsoBased(), true);
        eq("MinguoChronology.INSTANCE.isIsoBased()", MinguoChronology.INSTANCE.isIsoBased(), true);
        eq("ThaiBuddhistChronology.INSTANCE.isIsoBased()", ThaiBuddhistChronology.INSTANCE.isIsoBased(), true);
        eq("HijrahChronology.INSTANCE.isIsoBased()", HijrahChronology.INSTANCE.isIsoBased(), false);

        // and the agreement that matters: the same instant, two ways
        eq("LocalDateTime.of(2026, 3, 15, 12, 0, 0).toEpochSecond(ZoneOffset.UTC)", LocalDateTime.of(2026, 3, 15, 12, 0, 0).toEpochSecond(ZoneOffset.UTC), 1773576000L);

        // --- Clock.tickMillis: a property, because the value is the wall clock ---
        //
        // The whole point of the member is the truncation, so that is what is asserted rather than
        // an instant nobody can predict.
        Clock ticking = Clock.tickMillis(ZoneOffset.UTC);
        eq("tickMillis keeps its zone", ticking.getZone().toString(), "Z");
        eq("tickMillis truncates to whole milliseconds",
                ticking.instant().getNano() % 1_000_000L, 0L);
        eq("tickMillis millis agrees with its instant",
                ticking.millis(), ticking.instant().toEpochMilli());
        // Finer than tickSeconds and coarser than the system clock, which is the family it joins.
        eq("tickMillis is finer than tickSeconds",
                Clock.tickSeconds(ZoneOffset.UTC).instant().getNano() % 1_000_000L, 0L);

        // --- what has to be refused ---
        throwsToo("until(null)", NullPointerException.class,
                () -> Instant.EPOCH.until(null));
        throwsToo("toEpochSecond(null)", NullPointerException.class,
                () -> OffsetTime.parse("12:00:00Z").toEpochSecond(null));
        throwsToo("epochSecond(null offset)", NullPointerException.class,
                () -> IsoChronology.INSTANCE.epochSecond(2026, 3, 15, 12, 0, 0, null));
        throwsToo("epochSecond(null era)", NullPointerException.class,
                () -> MinguoChronology.INSTANCE.epochSecond(null, 1, 1, 1, 0, 0, 0,
                        ZoneOffset.UTC));
        // 29 February in a year that has none: the message names the year, which is the whole
        // reason IsoChronology overrides the default instead of inheriting it.
        throwsToo("epochSecond(2026-02-29)", DateTimeException.class,
                () -> IsoChronology.INSTANCE.epochSecond(2026, 2, 29, 0, 0, 0, ZoneOffset.UTC));
        throwsToo("epochSecond(2026-04-31)", DateTimeException.class,
                () -> IsoChronology.INSTANCE.epochSecond(2026, 4, 31, 0, 0, 0, ZoneOffset.UTC));
        throwsToo("epochSecond(month 13)", DateTimeException.class,
                () -> IsoChronology.INSTANCE.epochSecond(2026, 13, 1, 0, 0, 0, ZoneOffset.UTC));
        throwsToo("epochSecond(hour 24)", DateTimeException.class,
                () -> IsoChronology.INSTANCE.epochSecond(2026, 3, 15, 24, 0, 0, ZoneOffset.UTC));
        throwsToo("epochSecond(minute 60)", DateTimeException.class,
                () -> IsoChronology.INSTANCE.epochSecond(2026, 3, 15, 0, 60, 0, ZoneOffset.UTC));
        throwsToo("epochSecond(second 60)", DateTimeException.class,
                () -> IsoChronology.INSTANCE.epochSecond(2026, 3, 15, 0, 0, 60, ZoneOffset.UTC));
        // And one that must NOT throw: 29 February in a leap year.
        eq("epochSecond(2024-02-29) is accepted",
                IsoChronology.INSTANCE.epochSecond(2024, 2, 29, 0, 0, 0, ZoneOffset.UTC) > 0, true);

        // --- the override and the default have to agree ---
        //
        // IsoChronology.epochSecond does the arithmetic directly where Chronology's default builds
        // a LocalDate and asks it. Two code paths for one answer is exactly where a copied member
        // goes wrong, so they are held against each other over a range rather than at a point.
        int same = 0;
        for (int year = 1890; year <= 2130; year += 7) {
            for (int month = 1; month <= 12; month++) {
                long direct = IsoChronology.INSTANCE.epochSecond(
                        year, month, 15, 13, 7, 29, ZoneOffset.ofHours(-3));
                long viaDate = LocalDateTime.of(year, month, 15, 13, 7, 29)
                        .toEpochSecond(ZoneOffset.ofHours(-3));
                if (direct == viaDate) {
                    same++;
                } else {
                    eq("epochSecond(" + year + "-" + month + ")", direct, viaDate);
                }
            }
        }
        eq("the two paths agree everywhere tried", same, 420);
        checked += same;

        // The three non-ISO chronologies reach the same instant from their own year numbering,
        // which is what Chronology's default is for.
        eq("Minguo 115 is 2026",
                MinguoChronology.INSTANCE.epochSecond(115, 3, 15, 12, 0, 0, ZoneOffset.UTC),
                IsoChronology.INSTANCE.epochSecond(2026, 3, 15, 12, 0, 0, ZoneOffset.UTC));
        eq("ThaiBuddhist 2569 is 2026",
                ThaiBuddhistChronology.INSTANCE.epochSecond(2569, 3, 15, 12, 0, 0, ZoneOffset.UTC),
                IsoChronology.INSTANCE.epochSecond(2026, 3, 15, 12, 0, 0, ZoneOffset.UTC));

        System.out.println("checked " + checked + " assertions, " + failed + " mismatches");
        if (failed > 0) {
            System.exit(1);
        }
    }
}
