#!/bin/bash
# Rewrites the "# consumers" section of seeds.txt from what the tsbMobile consumers reference.
#
#   compiler/cocoatouch/prune/consumer-seeds.sh [rapidfx-checkout] [tsbRapidJ-checkout]
#
# The consumers are the only code that names binding classes (a form compiles against tsb.mobile
# and never sees them). Both `swing-ios` modules import classes by name, never with wildcards, so
# a grep over the sources is exact. Run it whenever swing-ios gains a binding class, then rebuild.
set -euo pipefail

HERE=$(cd "$(dirname "$0")" && pwd)
RAPIDFX=${1:-$HERE/../../../../rapidfx}
RAPIDJ=${2:-$HERE/../../../../tsbRapidJ}
SEEDS=$HERE/seeds.txt

for dir in "$RAPIDFX/mobile/tsb-mobile/swing-ios/src/main/java" "$RAPIDJ/mobile/swing-ios/src/main/java"; do
    if [ ! -d "$dir" ]; then
        echo "not a consumer checkout: $dir" >&2
        exit 1
    fi
done

FOUND=$(grep -rhoE 'org\.robovm\.apple\.[a-z]+\.[A-Za-z0-9]+' \
    "$RAPIDFX/mobile/tsb-mobile/swing-ios/src/main/java" \
    "$RAPIDJ/mobile/swing-ios/src/main/java" | sort -u)

{
    sed -n '1,/^# consumers/p' "$SEEDS"
    echo "# (generated by consumer-seeds.sh on $(date +%Y-%m-%d) from rapidfx and tsbRapidJ swing-ios — do not edit by hand)"
    echo "$FOUND"
    sed -n '/^# end consumers/,$p' "$SEEDS"
} > "$SEEDS.new"
mv "$SEEDS.new" "$SEEDS"
echo "$(echo "$FOUND" | wc -l | tr -d ' ') consumer seeds written to $SEEDS"
